replicaCount: 1

image:
  repository: 713881788927.dkr.ecr.ap-south-1.amazonaws.com/myapp
  tag: "8abf7190062f1be912b0bd06f1a546c68b61a443"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

env:
  APP_VERSION: "3.0.0"
  ENV: "staging"
