replicaCount: 1

image:
  repository: 713881788927.dkr.ecr.ap-south-1.amazonaws.com/myapp
  tag: "a69896434fcea27626b98d0529acb6d318156ceb"
  pullPolicy: Never

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

env:
  APP_VERSION: "3.0.0"
  ENV: "staging"
